### ISSUE TITLE
GitHub Actionsワークフローの改善

### ISSUE THREAD

**Issue by lemo-nade-room** [lemo-nade-room/event-store-adapter-swift-support#6]
## 概要

現在の単一のCIワークフローを、[event-store-adapter-swift](https://github.com/lemo-nade-room/event-store-adapter-swift)リポジトリを参考に改善することを提案します。

### 単一ワークフローの課題
現在の`.github/workflows/ci.yaml`では以下の問題があります：
- `lint`, `build`, `test`が単一ワークフローで依存関係がある
- フォーマットエラーだけでもテストまで実行されない
- 各ジョブの独立性が低い

### Swift環境の複雑性
- `ubuntu-latest`で`swift-actions/setup-swift@v2`を使用してSwift 6.0を明示的にインストール
- 標準のUbuntuに含まれるSwiftが活用されていない

### スケジューリングの欠如
- 1日1回の定期テストが設定されていない
- 継続的な品質監視ができていない

#### `swift-format.yaml` (フォーマット専用)
```yaml
name: Swift Format
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - ".github/workflows/swift-format.yaml"
      - "**.swift"
      - ".swift-format"

jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: swift format lint -s --configuration .swift-format -r Sources Tests Package.swift
```

#### `swift-test.yaml` (テスト専用)
```yaml
name: Swift Testing
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - ".github/workflows/swift-test.yaml"
      - "**.swift"
      - "Package.resolved"
  schedule:
    - cron: '0 0 * * *'  # 毎日午前0時に実行

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: swift-build-package-resolved-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('Package.resolved') }}
          path: .build
      - run: swift build
      - run: swift test
```

### 2. 標準Swift環境の活用

現在：
```yaml
- uses: swift-actions/setup-swift@v2
  with:
    swift-version: "6.0"
```

提案：
```yaml
# setup-swiftアクションを削除し、ubuntu-latest標準のSwiftを使用
# （バージョン確認用）
- run: swift --version
```

### 1. 並列実行によるCI高速化
- フォーマットチェックとテストが並列実行
- フォーマットエラーがあってもテストは実行される
- ジョブの独立性向上

### 2. 環境の簡素化
- `ubuntu-latest`標準のSwiftを使用
- 外部アクションへの依存を削減
- セットアップ時間の短縮

### 3. 継続的品質監視
- 1日1回の定期テスト実行
- 依存関係の問題を早期発見
- リグレッションの迅速な検出

## 参考実装

[event-store-adapter-swift](https://github.com/lemo-nade-room/event-store-adapter-swift)では以下のワークフロー構成が採用されています：

- `swift-format.yaml`: フォーマットチェック専用
- `swift-test.yaml`: テスト専用（スケジュール付き）
- `docc-github-pages.yaml`: ドキュメント生成

### 必要な変更
- [ ] 既存の`.github/workflows/ci.yaml`を削除
- [ ] `.github/workflows/swift-format.yaml`を作成
- [ ] `.github/workflows/swift-test.yaml`を作成
- [ ] README.mdのCIバッジ更新

### 削除対象
```bash
# 削除するファイル
.github/workflows/ci.yaml
```

### 作成対象
```bash
# 新規作成するファイル
.github/workflows/swift-format.yaml
.github/workflows/swift-test.yaml
```

### Ubuntu標準Swiftの使用
- Ubuntu 22.04/24.04にはSwift 5.x系が標準搭載
- Swift 6.0のサポート状況を確認が必要
- 必要に応じて最小限のセットアップのみ実行

### スケジューリング
- `cron: '0 0 * * *'`で毎日午前0時（UTC）に実行
- 外部依存関係の変更を定期的に検知

### キャッシュ戦略
- `.build`ディレクトリのキャッシュを維持
- `Package.resolved`ハッシュベースのキャッシュキー

## 互換性

- Swift 6.0以降の要求は維持
- 既存のビルド・テスト動作は完全に保持
- CIの実行結果に影響なし

## 期待される効果

1. **CI実行時間の短縮**: 並列実行による高速化
2. **保守性の向上**: ワークフローの責務分離
3. **継続的品質保証**: 定期テストによる品質維持
4. **環境依存の削減**: 標準環境の活用

## 実装タイムライン

本改善は既存機能を再構成するだけのため、短期間で実装可能です。
