### ISSUE TITLE
Dependabotによる自動依存関係更新の設定

### ISSUE THREAD

**Issue by lemo-nade-room** [lemo-nade-room/event-store-adapter-swift-support#7]
## 概要

[event-store-adapter-swift](https://github.com/lemo-nade-room/event-store-adapter-swift)リポジトリを参考に、GitHub DependabotによるSwift Package Managerの依存関係自動更新を設定することを提案します。

### 依存関係管理の課題
- Swift Package Managerの依存関係が手動更新のみ
- セキュリティパッチや新機能の適用が遅れる可能性
- 依存関係の更新忘れによる技術的負債の蓄積

### 現在の依存関係
`Package.swift`で以下の依存関係を管理：
```swift
dependencies: [
    .package(url: "https://github.com/lemo-nade-room/event-store-adapter-swift.git", from: "1.0.0"),
    .package(url: "https://github.com/swiftlang/swift-syntax", from: "600.0.0"),
    .package(url: "https://github.com/pointfreeco/swift-macro-testing.git", from: "0.6.0"),
    .package(url: "https://github.com/swiftlang/swift-docc-plugin.git", from: "1.0.0"),
    .package(url: "https://github.com/apple/swift-distributed-actors.git", branch: "main"),
]
```

### Dependabot設定ファイルの追加

`.github/dependabot.yml`を作成：

```yaml
version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "lemo-nade-room"
    commit-message:
      prefix: "deps"
      include: "scope"
```

### 参考実装

[event-store-adapter-swift](https://github.com/lemo-nade-room/event-store-adapter-swift)では以下の設定が採用されています：

```yaml
version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "daily"
```

### 1. セキュリティの向上
- 依存関係の脆弱性が発見された際の迅速な対応
- セキュリティパッチの自動適用
- CVE（Common Vulnerabilities and Exposures）への早期対策

### 2. 保守性の向上
- 依存関係更新の自動化
- 人的ミスの削減
- 最新機能の恩恵を早期に享受

### 3. 開発効率の向上
- 手動更新作業の削減
- プルリクエストによる変更の可視化
- CIでの自動テストによる安全性確保

### 基本設定
- **package-ecosystem**: `"swift"` - Swift Package Manager対応
- **directory**: `"/"` - ルートディレクトリのPackage.swiftを監視
- **schedule.interval**: `"daily"` - 毎日依存関係をチェック

### 拡張設定（提案）
- **open-pull-requests-limit**: `10` - 同時オープンPR数の制限
- **reviewers**: 自動レビュアー設定
- **commit-message**: コミットメッセージの統一

### 自動更新対象
以下の依存関係が自動更新の対象となります：
- `event-store-adapter-swift`: セマンティックバージョニング対応
- `swift-syntax`: Swiftマクロ関連の最新機能
- `swift-macro-testing`: テスト機能の改善
- `swift-docc-plugin`: ドキュメント生成の改善

### 注意が必要な依存関係
- `swift-distributed-actors`: `branch: "main"`のため注意深い確認が必要

### 必要な変更
- [ ] `.github/dependabot.yml`ファイルの作成
- [ ] レビュープロセスの整備
- [ ] Dependabot PRの処理方針決定

### 作成対象
```bash
# 新規作成するファイル
.github/dependabot.yml
```

### PRの処理手順
1. **自動生成されたPR**をレビュー
2. **CIテストの結果**を確認
3. **破壊的変更**がないことを確認
4. **問題なければマージ**

### レビューポイント
- セマンティックバージョニングの適切性
- 破壊的変更（BREAKING CHANGES）の有無
- テスト結果の確認
- ドキュメントへの影響

### 自動更新の安全性
- CIテストによる動作確認
- セマンティックバージョニングによる安全性担保
- レビューによる人的チェック

### 緊急対応
- 脆弱性発見時の迅速な更新
- セキュリティアドバイザリの自動通知
- 重要度に応じた優先度付け

### 短期的効果
- 依存関係の最新化
- セキュリティリスクの軽減
- 手動作業の削減

### 長期的効果
- 技術的負債の削減
- 最新機能の活用
- 開発生産性の向上

## 実装タイムライン

本設定は単一ファイルの追加のため、即座に実装可能です。設定後、翌日から自動的にPRが生成され始めます。
